ARG BUILD_FROM
FROM $BUILD_FROM

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV LANG=C.UTF-8

RUN apk update && \
    apk add --no-cache \
        iw \
        hostapd \
        networkmanager \
        networkmanager-cli \
        iproute2 \
        procps \
        dnsmasq \
        nftables \
        tcpdump && \
    rm -rf /var/cache/apk/*

COPY hostapd.conf /
COPY dnsmasq.conf /
COPY nftables.conf /

COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]
